/**
 * Machine-readable catalog of reference recipes for discovery, docs, and tooling.
 * Category IDs match research/taxonomy.md (empirical harness shapes).
 */
export type RecipeCategory =
  | "candidate-action-selection"
  | "row-judgment"
  | "live-multi-judgment"
  | "confidence-front-door"
  | "verify-gate"
  | "composite-rubric"
  | "semantic-find"
  | "high-freq-reflex";

export type RecipeQuestionKind = "choice" | "score" | "noul";

export interface RecipeCatalogEntry {
  /** Stable id, matches path slug under recipes/<category>/ */
  id: string;
  name: string;
  category: RecipeCategory;
  description: string;
  /** Import path relative to package root (TypeScript source). */
  module: string;
  /** Exported runner function name. */
  runner: string;
  /** Question names and kinds used by the recipe. */
  questions: { name: string; kind: RecipeQuestionKind }[];
  /** Domain actions the policy may return (not including low-confidence / shadow overrides). */
  actions: string[];
  defaultMinConfidence: number;
  defaultOnLowConfidence: "review" | "escalate_llm" | "suppress" | "proceed";
  tags: string[];
}

export const catalog = [
  {
    id: "candidate-action-select",
    name: "Candidate Action Select",
    category: "candidate-action-selection",
    description: "Choice over a dynamic candidate set (+ optional stop Noul) for perception→act loops.",
    module: "recipes/candidate-action-selection/candidate-action-select.ts",
    runner: "runCandidateActionSelect",
    questions: [
      { name: "next", kind: "choice" },
      { name: "done", kind: "noul" },
    ],
    actions: ["<candidate-id>", "STOP"],
    defaultMinConfidence: 0.45,
    defaultOnLowConfidence: "review",
    tags: ["ui-grounding", "candidates", "computer-use"],
  },
  {
    id: "browser-next-action",
    name: "Browser Next Action",
    category: "candidate-action-selection",
    description: "Pick the next click/candidate in computer-use or wiki-race flows.",
    module: "recipes/candidate-action-selection/browser-next-action.ts",
    runner: "runBrowserNextAction",
    questions: [
      { name: "next", kind: "choice" },
      { name: "done", kind: "noul" },
    ],
    actions: ["<candidate-id>", "STOP"],
    defaultMinConfidence: 0.45,
    defaultOnLowConfidence: "review",
    tags: ["ui-grounding", "browser", "computer-use"],
  },
  {
    id: "keystroke-launcher",
    name: "Keystroke Launcher",
    category: "candidate-action-selection",
    description:
      "Per-keystroke intent Choice over launcher candidates; WAIT when unsure (dabit3-style oracle).",
    module: "recipes/candidate-action-selection/keystroke-launcher.ts",
    runner: "runKeystrokeLauncher",
    questions: [
      { name: "best", kind: "choice" },
      { name: "match_quality", kind: "score" },
      { name: "ready", kind: "noul" },
    ],
    actions: ["<candidate-id>", "NONE", "WAIT"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["launcher", "keystroke", "oracle", "candidates", "live", "proof"],
  },

  {
    id: "tool-picker",
    name: "Tool Picker",
    category: "candidate-action-selection",
    description: "Pick which tool to invoke next from a declared catalog, or decline.",
    module: "recipes/candidate-action-selection/tool-picker.ts",
    runner: "runToolPicker",
    questions: [
      { name: "tool", kind: "choice" },
      { name: "necessary", kind: "noul" },
    ],
    actions: ["<tool-id>", "none"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["tools", "planning", "candidates"],
  },
  {
    id: "skill-roster-pick",
    name: "Skill Roster Pick",
    category: "candidate-action-selection",
    description:
      "Suggest which agent skill to load next from a roster, or abstain (skill_suggestion / SkillRanker shape).",
    module: "recipes/candidate-action-selection/skill-roster-pick.ts",
    runner: "runSkillRosterPick",
    questions: [
      { name: "skill", kind: "choice" },
      { name: "needs_skill", kind: "noul" },
      { name: "fits_top", kind: "noul" },
    ],
    actions: ["<skill-id>", "none"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["skills", "skill-suggestion", "roster", "candidates", "skillranker"],
  },
  {
    id: "stop-or-continue",
    name: "Stop or Continue",
    category: "candidate-action-selection",
    description: "Decide whether an agent loop should keep going, stop, or ask the user.",
    module: "recipes/candidate-action-selection/stop-or-continue.ts",
    runner: "runStopOrContinue",
    questions: [
      { name: "disposition", kind: "choice" },
      { name: "progress", kind: "score" },
      { name: "stuck", kind: "noul" },
    ],
    actions: ["continue", "stop", "ask_user"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["loops", "control", "stop-noul"],
  },
  {
    id: "who-speaks-next",
    name: "Who Speaks Next",
    category: "candidate-action-selection",
    description:
      "Pick the next multi-agent speaker (agent id / user / none) with handoff + user-turn gates.",
    module: "recipes/agent-comm-harness/who-speaks-next.ts",
    runner: "runWhoSpeaksNext",
    questions: [
      { name: "next_speaker", kind: "choice" },
      { name: "progress", kind: "score" },
      { name: "needs_handoff", kind: "noul" },
      { name: "user_turn", kind: "noul" },
    ],
    actions: ["<agent-id>", "user", "none"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["agent-comm-harness", "multi-agent", "handoff", "selector", "candidates"],
  },
  {
    id: "row-semantic-match",
    name: "Row Semantic Match",
    category: "row-judgment",
    description: "Judge whether one JSON/DB row matches a natural-language predicate.",
    module: "recipes/row-judgment/row-semantic-match.ts",
    runner: "runRowSemanticMatch",
    questions: [
      { name: "matches", kind: "noul" },
      { name: "strength", kind: "score" },
    ],
    actions: ["include", "exclude", "review"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["structured-data-filter", "semantic-where", "data"],
  },
  {
    id: "model-router",
    name: "Model Router",
    category: "confidence-front-door",
    description: "Route a user prompt to cheap / mid / frontier tiers by difficulty and risk.",
    module: "recipes/confidence-front-door/model-router.ts",
    runner: "runModelRouter",
    questions: [
      { name: "tier", kind: "choice" },
      { name: "risk", kind: "score" },
    ],
    actions: ["cheap", "mid", "frontier"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "escalate_llm",
    tags: ["routing", "cost", "llm"],
  },
  {
    id: "model-cost-router",
    name: "Model Cost Router",
    category: "confidence-front-door",
    description:
      "Route prompts to cheap/mid/frontier with a cheap-first bias; escalate on low confidence.",
    module: "recipes/confidence-front-door/model-cost-router.ts",
    runner: "runModelCostRouter",
    questions: [
      { name: "tier", kind: "choice" },
      { name: "risk", kind: "score" },
    ],
    actions: ["cheap", "mid", "frontier"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "escalate_llm",
    tags: ["routing", "cost", "llm", "proof"],
  },
  {
    id: "alert-gate",
    name: "Alert Gate",
    category: "confidence-front-door",
    description: "Gate noisy automated alerts before they page a human.",
    module: "recipes/confidence-front-door/alert-gate.ts",
    runner: "runAlertGate",
    questions: [
      { name: "disposition", kind: "choice" },
      { name: "severity", kind: "score" },
      { name: "needs_human", kind: "noul" },
    ],
    actions: ["notify", "queue_review", "suppress"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["alerts", "paging", "on-call", "routing"],
  },
  {
    id: "inbox-triage",
    name: "Inbox Triage",
    category: "confidence-front-door",
    description: "Route inbound messages into bookings, orders, support, spam, or other.",
    module: "recipes/confidence-front-door/inbox-triage.ts",
    runner: "runInboxTriage",
    questions: [
      { name: "bucket", kind: "choice" },
      { name: "urgency", kind: "score" },
      { name: "is_customer", kind: "noul" },
    ],
    actions: ["bookings", "orders", "support", "spam", "other"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["email", "inbox", "triage", "routing"],
  },
  {
    id: "incident-severity",
    name: "Incident Severity",
    category: "confidence-front-door",
    description: "Classify incident severity from signals, blast radius, and customer impact.",
    module: "recipes/confidence-front-door/incident-severity.ts",
    runner: "runIncidentSeverity",
    questions: [
      { name: "severity", kind: "choice" },
      { name: "blast_radius", kind: "score" },
      { name: "customer_facing", kind: "noul" },
    ],
    actions: ["sev1", "sev2", "sev3", "sev4"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["incident", "severity", "routing"],
  },
  {
    id: "oncall-page",
    name: "On-call Page",
    category: "confidence-front-door",
    description: "Decide whether an event should page on-call, soft-notify, defer, or be ignored.",
    module: "recipes/confidence-front-door/oncall-page.ts",
    runner: "runOncallPage",
    questions: [
      { name: "action", kind: "choice" },
      { name: "urgency", kind: "score" },
      { name: "actionable", kind: "noul" },
    ],
    actions: ["page_now", "notify_slack", "defer", "ignore"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["on-call", "paging", "routing"],
  },
  {
    id: "message-route",
    name: "Message Route",
    category: "confidence-front-door",
    description:
      "Route an inter-agent message to a specialist, broadcast, drop, or escalate (secret-aware).",
    module: "recipes/agent-comm-harness/message-route.ts",
    runner: "runMessageRoute",
    questions: [
      { name: "route", kind: "choice" },
      { name: "urgency", kind: "score" },
      { name: "contains_secrets", kind: "noul" },
      { name: "escalate", kind: "noul" },
    ],
    actions: ["<specialist-id>", "broadcast", "drop", "escalate"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["agent-comm-harness", "routing", "multi-agent", "bus", "secrets"],
  },
  {
    id: "llm-verifier",
    name: "LLM Verifier",
    category: "verify-gate",
    description: "Verify an LLM or tool output before it ships.",
    module: "recipes/verify-gate/llm-verifier.ts",
    runner: "runLlmVerifier",
    questions: [
      { name: "verdict", kind: "choice" },
      { name: "grounded", kind: "noul" },
      { name: "jailbreak", kind: "noul" },
    ],
    actions: ["allow", "revise", "block"],
    defaultMinConfidence: 0.6,
    defaultOnLowConfidence: "review",
    tags: ["safety", "verification", "gate"],
  },
  {
    id: "ship-gate",
    name: "Ship Gate",
    category: "verify-gate",
    description:
      "Allow / revise / block a candidate output before ship; suppress on low confidence.",
    module: "recipes/verify-gate/ship-gate.ts",
    runner: "runShipGate",
    questions: [
      { name: "verdict", kind: "choice" },
      { name: "grounded", kind: "noul" },
      { name: "unsafe", kind: "noul" },
    ],
    actions: ["ship", "revise", "block"],
    defaultMinConfidence: 0.65,
    defaultOnLowConfidence: "suppress",
    tags: ["safety", "verification", "ship", "proof"],
  },
  {
    id: "injection-check",
    name: "Injection Check",
    category: "verify-gate",
    description: "Detect prompt injection / jailbreak attempts in untrusted input.",
    module: "recipes/verify-gate/injection-check.ts",
    runner: "runInjectionCheck",
    questions: [
      { name: "disposition", kind: "choice" },
      { name: "severity", kind: "score" },
      { name: "is_injection", kind: "noul" },
    ],
    actions: ["pass", "sanitize", "block"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["injection", "security", "gate"],
  },
  {
    id: "tool-call-allowlist",
    name: "Tool Call Allowlist",
    category: "verify-gate",
    description: "Gate a proposed tool call against policy / allowlist before execution.",
    module: "recipes/verify-gate/tool-call-allowlist.ts",
    runner: "runToolCallAllowlist",
    questions: [
      { name: "verdict", kind: "choice" },
      { name: "args_safe", kind: "noul" },
      { name: "intent_aligned", kind: "noul" },
    ],
    actions: ["allow", "deny", "require_confirm"],
    defaultMinConfidence: 0.6,
    defaultOnLowConfidence: "review",
    tags: ["tools", "allowlist", "gate"],
  },
  {
    id: "shell-command-gate",
    name: "Shell Command Gate",
    category: "verify-gate",
    description:
      "CLI command string → allow / deny / ask with irreversible class + known-safe allowlist (fx-style).",
    module: "recipes/verify-gate/shell-command-gate.ts",
    runner: "runShellCommandGate",
    questions: [
      { name: "verdict", kind: "choice" },
      { name: "risk_class", kind: "choice" },
      { name: "irreversible", kind: "noul" },
      { name: "intent_ok", kind: "noul" },
      { name: "blast_radius", kind: "score" },
    ],
    actions: ["allow", "deny", "ask"],
    defaultMinConfidence: 0.6,
    defaultOnLowConfidence: "suppress",
    tags: ["shell", "fx", "cli", "allowlist", "safety", "verify-gate", "proof"],
  },
  {
    id: "agent-stuck-drift",
    name: "Agent Stuck Drift",
    category: "verify-gate",
    description:
      "Foreman-style supervisor: stuck + drift + tests + progress → continue / nudge / recover / stop_review.",
    module: "recipes/verify-gate/agent-stuck-drift.ts",
    runner: "runAgentStuckDrift",
    questions: [
      { name: "stuck", kind: "noul" },
      { name: "drifted", kind: "noul" },
      { name: "progress", kind: "score" },
      { name: "tests_pass", kind: "noul" },
      { name: "disposition", kind: "choice" },
    ],
    actions: ["continue", "nudge", "recover", "stop_review"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["foreman", "supervisor", "stuck", "drift", "agents", "verify-gate", "proof"],
  },
  {
    id: "pr-risk-gate",
    name: "PR Risk Gate",
    category: "verify-gate",
    description:
      "PR/diff severity gate: risk + secrets + test gap → merge_ok / request_changes / block.",
    module: "recipes/verify-gate/pr-risk-gate.ts",
    runner: "runPrRiskGate",
    questions: [
      { name: "risk", kind: "score" },
      { name: "severity", kind: "choice" },
      { name: "secrets", kind: "noul" },
      { name: "security_issue", kind: "noul" },
      { name: "test_gap", kind: "noul" },
      { name: "correctness", kind: "score" },
      { name: "disposition", kind: "choice" },
    ],
    actions: ["merge_ok", "request_changes", "block"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["pr", "diff", "review", "severity", "secrets", "verify-gate", "proof"],
  },

  {
    id: "tool-gate",
    name: "Tool Gate",
    category: "verify-gate",
    description:
      "Gate a proposed tool call by risk class, policy, blast radius, then handoff disposition.",
    module: "recipes/agent-comm-harness/tool-gate.ts",
    runner: "runToolGate",
    questions: [
      { name: "risk_class", kind: "choice" },
      { name: "policy_ok", kind: "noul" },
      { name: "irreversible", kind: "noul" },
      { name: "blast_radius", kind: "score" },
      { name: "handoff", kind: "choice" },
    ],
    actions: ["continue", "ask_user", "escalate_specialist", "abort"],
    defaultMinConfidence: 0.6,
    defaultOnLowConfidence: "suppress",
    tags: ["agent-comm", "agent-comm-harness", "tools", "gate"],
  },
  {
    id: "rubric-scorer",
    name: "Rubric Scorer",
    category: "composite-rubric",
    description: "Score a submission against an ordered multi-dimension rubric.",
    module: "recipes/composite-rubric/rubric-scorer.ts",
    runner: "runRubricScorer",
    questions: [{ name: "<dimension-id>", kind: "score" }],
    actions: ["pass", "revise", "fail"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["rubric", "scoring", "multi-score"],
  },
  {
    id: "typewriter-panel",
    name: "Typewriter Panel",
    category: "live-multi-judgment",
    description: "Live multi-score editor panel: tone, clarity, urgency, AI-written, intent on a draft.",
    module: "recipes/live-multi-judgment/typewriter-panel.ts",
    runner: "runTypewriterPanel",
    questions: [
      { name: "tone", kind: "score" },
      { name: "clarity", kind: "score" },
      { name: "urgent", kind: "noul" },
      { name: "ai_written", kind: "noul" },
      { name: "intent", kind: "choice" },
    ],
    actions: ["update_ui"],
    defaultMinConfidence: 0.4,
    defaultOnLowConfidence: "proceed",
    tags: ["live", "fan-out", "editor", "typewriter"],
  },
  {
    id: "ticket-fanout",
    name: "Ticket Fanout",
    category: "live-multi-judgment",
    description: "Speculative multi-question ticket briefing in one RTT; route or escalate.",
    module: "recipes/live-multi-judgment/ticket-fanout.ts",
    runner: "runTicketFanout",
    questions: [
      { name: "category", kind: "choice" },
      { name: "severity", kind: "score" },
      { name: "refund", kind: "noul" },
      { name: "has_repro", kind: "noul" },
      { name: "frustration", kind: "score" },
    ],
    actions: ["billing", "bug", "how_to", "account", "other", "escalate"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["live", "fan-out", "support", "ticket"],
  },
  {
    id: "line-semantic-find",
    name: "Line Semantic Find",
    category: "semantic-find",
    description: "Pick the best doc line for an NL query, or NONE if nothing fits.",
    module: "recipes/semantic-find/line-semantic-find.ts",
    runner: "runLineSemanticFind",
    questions: [
      { name: "best", kind: "choice" },
      { name: "answer_exists", kind: "noul" },
    ],
    actions: ["<line-id>", "NONE"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["search", "rank", "lines", "rag"],
  },
  {
    id: "span-pick",
    name: "Span Pick",
    category: "semantic-find",
    description: "Pick a pre-parsed value/span that satisfies a request, or NONE.",
    module: "recipes/semantic-find/span-pick.ts",
    runner: "runSpanPick",
    questions: [
      { name: "span", kind: "choice" },
      { name: "none_fit", kind: "noul" },
    ],
    actions: ["<span-id>", "NONE"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["extraction", "spans", "candidates"],
  },
  {
    id: "mm-buy-sell",
    name: "MM Buy Sell",
    category: "high-freq-reflex",
    description: "Block-time buy/sell/hold reflex from a compact book snapshot.",
    module: "recipes/high-freq-reflex/mm-buy-sell.ts",
    runner: "runMmBuySell",
    questions: [
      { name: "side", kind: "choice" },
      { name: "edge", kind: "score" },
    ],
    actions: ["buy", "sell", "hold"],
    defaultMinConfidence: 0.45,
    defaultOnLowConfidence: "suppress",
    tags: ["latency", "trading", "reflex"],
  },
  {
    id: "hot-path-allow",
    name: "Hot Path Allow",
    category: "high-freq-reflex",
    description: "Sub-100ms allow/deny reflex on a compact hot-path event.",
    module: "recipes/high-freq-reflex/hot-path-allow.ts",
    runner: "runHotPathAllow",
    questions: [
      { name: "allow", kind: "noul" },
      { name: "severity", kind: "score" },
    ],
    actions: ["allow", "deny"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "review",
    tags: ["latency", "gate", "reflex"],
  },
  {
    id: "prediction-market-gate",
    name: "Prediction Market Gate",
    category: "high-freq-reflex",
    description:
      "Arb / liquidity-vs-edge gate for prediction markets (post, cancel, hedge, or skip).",
    module: "recipes/prediction-market-gate/prediction-market-gate.ts",
    runner: "runPredictionMarketGate",
    questions: [
      { name: "is_arb", kind: "noul" },
      { name: "edge_after_costs", kind: "score" },
      { name: "depth_ok", kind: "noul" },
      { name: "fair_fresh", kind: "noul" },
      { name: "tradeoff", kind: "score" },
      { name: "action", kind: "choice" },
    ],
    actions: ["post_bid", "cancel", "hedge_other", "skip"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "suppress",
    tags: ["latency", "polymarket", "prediction-market", "arb", "liquidity", "reflex"],
  },
  {
    id: "sports-bet-gate",
    name: "Sports Bet Gate",
    category: "high-freq-reflex",
    description: "Bet / no-bet / shop-elsewhere gate with edge score and CLV filter.",
    module: "recipes/sports-bet-gate/sports-bet-gate.ts",
    runner: "runSportsBetGate",
    questions: [
      { name: "bet", kind: "noul" },
      { name: "book", kind: "choice" },
      { name: "edge", kind: "score" },
      { name: "meets_clv_filter", kind: "noul" },
      { name: "liquidity_ok", kind: "score" },
    ],
    actions: ["bet", "no_bet", "shop_elsewhere"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "suppress",
    tags: ["sports-bet", "clv", "reflex", "latency"],
  },
  {
    id: "swarm-consensus",
    name: "Swarm Consensus",
    category: "composite-rubric",
    description:
      "Judge multi-agent debate: consensus?, winner, evidence quality, fatal objection → disposition.",
    module: "recipes/composite-rubric/swarm-consensus.ts",
    runner: "runSwarmConsensus",
    questions: [
      { name: "consensus_reached", kind: "noul" },
      { name: "winner", kind: "choice" },
      { name: "evidence_quality", kind: "score" },
      { name: "fatal_objection", kind: "noul" },
      { name: "disposition", kind: "choice" },
    ],
    actions: ["adopt", "another_round", "escalate_human", "abort"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["swarm", "debate", "consensus", "multi-agent", "judge", "agent-comm-harness"],
  },
  {
    id: "order-allow-deny",
    name: "Order Allow Deny",
    category: "high-freq-reflex",
    description:
      "Pre-trade allow/deny/cancel/hold gate with edge, risk, and news-conflict checks.",
    module: "recipes/high-freq-reflex/order-allow-deny.ts",
    runner: "runOrderAllowDeny",
    questions: [
      { name: "allow_order", kind: "noul" },
      { name: "side_intent", kind: "choice" },
      { name: "edge", kind: "score" },
      { name: "risk", kind: "score" },
      { name: "news_conflict", kind: "noul" },
    ],
    actions: ["allow", "deny", "cancel", "hold"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "suppress",
    tags: ["latency", "trading", "gate", "risk", "reflex"],
  },
  {
    id: "fraud-score-gate",
    name: "Fraud Score Gate",
    category: "high-freq-reflex",
    description:
      "Score payment/login fraud risk and dispose: allow, step-up, deny, or review.",
    module: "recipes/high-freq-reflex/fraud-score-gate.ts",
    runner: "runFraudScoreGate",
    questions: [
      { name: "fraud_risk", kind: "score" },
      { name: "disposition", kind: "choice" },
      { name: "device_anomaly", kind: "noul" },
      { name: "velocity_anomaly", kind: "noul" },
    ],
    actions: ["allow", "step_up", "deny", "review"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["fraud", "payments", "login", "risk", "latency", "reflex"],
  },
  {
    id: "esports-reflex",
    name: "Esports Reflex",
    category: "candidate-action-selection",
    description:
      "Pick the next legal game action from engine candidates; stop or regroup on Noul.",
    module: "recipes/candidate-action-selection/esports-reflex.ts",
    runner: "runEsportsReflex",
    questions: [
      { name: "legal_action", kind: "choice" },
      { name: "urgency", kind: "score" },
      { name: "done", kind: "noul" },
      { name: "regroup", kind: "noul" },
    ],
    actions: ["<candidate-id>", "STOP", "REGROUP"],
    defaultMinConfidence: 0.45,
    defaultOnLowConfidence: "review",
    tags: ["games", "esports", "reflex", "candidates", "latency"],
  },
  {
    id: "edge-content-mod",
    name: "Edge Content Mod",
    category: "verify-gate",
    description:
      "Edge moderation: allow / warn / review / block with hate/sexual/self-harm/spam fan-out.",
    module: "recipes/verify-gate/edge-content-mod.ts",
    runner: "runEdgeContentMod",
    questions: [
      { name: "verdict", kind: "choice" },
      { name: "severity", kind: "score" },
      { name: "hate", kind: "noul" },
      { name: "sexual", kind: "noul" },
      { name: "self_harm", kind: "noul" },
      { name: "spam", kind: "noul" },
    ],
    actions: ["allow", "warn", "review", "block"],
    defaultMinConfidence: 0.6,
    defaultOnLowConfidence: "review",
    tags: ["moderation", "safety", "edge", "live", "guardrails"],
  },
  {
    id: "cyber-alert-triage",
    name: "Cyber Alert Triage",
    category: "confidence-front-door",
    description:
      "Triage SOC/SIEM alerts: notify, queue for review, or suppress — with actionable + needs_human gates.",
    module: "recipes/confidence-front-door/cyber-alert-triage.ts",
    runner: "runCyberAlertTriage",
    questions: [
      { name: "disposition", kind: "choice" },
      { name: "severity", kind: "score" },
      { name: "needs_human", kind: "noul" },
      { name: "actionable", kind: "noul" },
    ],
    actions: ["notify", "queue_review", "suppress"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "review",
    tags: ["alerts", "security", "soc", "paging", "on-call", "triage"],
  },
  {
    id: "rtb-bid-gate",
    name: "RTB Bid Gate",
    category: "high-freq-reflex",
    description:
      "Pre-bid filter: bid, pass, or block on brand-safety + IVT risk for RTB auctions.",
    module: "recipes/high-freq-reflex/rtb-bid-gate.ts",
    runner: "runRtbBidGate",
    questions: [
      { name: "bid", kind: "noul" },
      { name: "brand_safety", kind: "choice" },
      { name: "ivt_risk", kind: "score" },
      { name: "creative_page_align", kind: "noul" },
    ],
    actions: ["bid", "pass", "block"],
    defaultMinConfidence: 0.5,
    defaultOnLowConfidence: "suppress",
    tags: ["ads", "rtb", "brand-safety", "ivt", "latency", "reflex"],
  },
  {
    id: "tool-exec-gate",
    name: "Tool Exec Gate",
    category: "verify-gate",
    description:
      "Allow/deny tool execution with risk class, policy Noul, and blast-radius Score.",
    module: "recipes/agent-comm-harness/tool-exec-gate.ts",
    runner: "runToolExecGate",
    questions: [
      { name: "risk_class", kind: "choice" },
      { name: "policy_ok", kind: "noul" },
      { name: "irreversible", kind: "noul" },
      { name: "blast_radius", kind: "score" },
    ],
    actions: ["exec", "ask_user", "escalate", "deny"],
    defaultMinConfidence: 0.55,
    defaultOnLowConfidence: "suppress",
    tags: ["agent-comm", "agent-comm-harness", "tools", "allowlist", "gate"],
  },
] as const satisfies readonly RecipeCatalogEntry[];

export function getRecipe(id: string): RecipeCatalogEntry | undefined {
  return catalog.find((r) => r.id === id);
}

export function recipesByCategory(category: RecipeCategory): RecipeCatalogEntry[] {
  return catalog.filter((r) => r.category === category);
}
